### ISSUE TITLE
bug: The party with closest quotient shows a negative number for margin in votes

### ISSUE THREAD

**Issue by oysor** [Project-Lavinia/Lavinia-client#206]
Triggers when:
Første delingstall: 1
Sperregrense for utjevningsmandater: 3.7
Sperregrense for distriktmandater: 9.5

![bug-kvotient](https://user-images.githubusercontent.com/23212478/89098609-6eeba880-d3e9-11ea-8577-b86559b7d497.png)

**Comment by simendag** [comment]
I'm not sure this is a bug. Notice that you put the district threshold to 9.5%, and that the party with negative margin is below that limit.

Notice that if you move the threshold to 8.6%, that same party receives a seat immediately, because it is within the threshold.

You can consider negative margins to represent "unfairness" within the district in this context, to some degree -- without the district threshold, they would have been "x votes" ahead of the current winner.

**Comment by simendag** [comment]
@Log234 might want to chime in here and see if he agrees with my reasoning, as he has a better grasp on this than I do.

**Comment by Log234** [comment]
I was initially somewhat confused by this, but Simen's analysis cleared it up for me. The party would have won 2 district seats, but cannot win any due to the limit. So they do actually have more votes than they would need to win the seat, hence the negative number of votes.

**Comment by simendag** [comment]
I'm closing this in favour of the referenced issue above.
